### ISSUE TITLE
Copilot chat hangs

### ISSUE THREAD

**Issue by dov** [chep/copilot-chat.el#28]
Every now and then copilot-chat hangs on me. When this happens, when I press enter, I will never get an answer. Unfortunately, I don't have a reproducible scenario.

I have looked for a emacs buffer that may contain a clue what happened, and the only buffer that matches "chat" that may contain something is *copilot-chat-curl-stderr* which contains:

```
Process copilot-chat-curl stderr finished
```

When this happens, the only way back into chat that I have found is to restart Emacs. After restarting emacs and rerunning `(copilot-chat-shell-maker-display)` , I'm back to into the chat again. Is there a less disruptive way of restarting the chat?

I'm running commit 3516109 from master.

**Comment by kassick** [comment]
Could you try with bafdb518e4beb52e0183719971563a776e4b20e6 ?

I had the same issue -- in the end it was caused by the API returning an error payload that was not handled / displayed to the user (in my case, I was reaching the token limit). @chep has recently merged a change I've proposed to handle this situation.

If the API is returning some error code, latest version will help you to see what's happening ;)

Alternatively, you can update `copilot-chat--curl-make-process` to add `-vvv` to the curl options to get more info in stderr and/or `debug-on-entry`/`edebug` `copilot-chat--curl-analyze-response` to see what (if any) data is being returned by the API.

**Comment by chep** [comment]
It's not the answer you expect but for your information, you can use `copilot-chat-display` even with shell-maker as frontend.

**Comment by chep** [comment]
Did you try killing the buffer and calling `copilot-chat-reset` ? It is strange to have to restart emacs.

**Comment by dov** [comment]
> Did you try killing the buffer and calling `copilot-chat-reset` ? It is strange to have to restart emacs.

Thanks! This was the immediate command that I was looking for! :-) Now I can at least restart the chat shell when I get stuck!

I'll try the other remedies as well.

**Comment by chep** [comment]
Are you using last revision as @kassick said ?

**Comment by dov** [comment]
Yes, certainly. Everything works great now!
